package Ninja_Tests;

//Generated by Selenium IDE

import NinjaPages.NinjaAddToCart;
import NinjaPages.NinjaLoginPage;
import NinjaPages.NinjaPurchaseItem;
import NinjaPages.NinjaRegisterPage;
import PagesContract.IAddToCartPage;
import PagesContract.ILoginPage;
import PagesContract.IPurchasePage;
import PagesContract.IRegisterPage;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.Test;
import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;
import org.junit.Before;
import org.junit.After;
import org.junit.Assert;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;

import java.nio.file.Paths;
import java.util.*;
import java.io.IOException;


public class NinjaPurchaseTests {
    private Logger logger;
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    JsonReader jsonReader;

    @Before
    public void setUp() throws IOException {
        System.setProperty("webdriver.chrome.driver", "src\\test\\resources\\chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        logger = LogManager.getLogger(NinjaPurchaseTests.class);
        jsonReader = new JsonReader();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    public void addToCart() {
        IAddToCartPage ninjaLoginPage = new NinjaAddToCart(driver);
        ninjaLoginPage.navigateToHomePage();
        logger.debug("Adding product to cart");
        ninjaLoginPage.addProductToCart();
    }

   @Test
    public void purchase() {
	   logger.debug("##### Starting purchase item functionality test #####");
	   IPurchasePage ninjaPurchaseItem = new NinjaPurchaseItem(driver);
	   
	   logger.debug("Adding item to cart");
	   this.addToCart();
       try {
           Thread.sleep(2000);
       } catch (InterruptedException e) {
           // TODO Auto-generated catch block
           e.printStackTrace();
       }
	   
	   logger.debug("Reading test inputs from json");
	   var testInputs = jsonReader.read("src/test/resources/PurchaseTestInput.json");
	   
	   logger.debug("Navigate to cart page");
	   ninjaPurchaseItem.navigateToCartPage();
	   
	   logger.debug("Navigate to checkout page");
	   ninjaPurchaseItem.navigateToPurchasePage();
	   
	   logger.debug("Fill purchase form");
	   ninjaPurchaseItem.FillPurchaseForm(testInputs);
	   
	   logger.debug("Submit form");
	   ninjaPurchaseItem.clickSubmit();
	   
       logger.debug("Verify that the purchase was done successfully");
       Assert.assertTrue(ninjaPurchaseItem.isPurchasedSuccessfully());
       logger.debug("##### Purchase item test finished successfully! #####");

    }



    public static void main(String args[]) {
        JUnitCore junit = new JUnitCore();
        junit.addListener(new TextListener(System.out));
        Logger logger = LogManager.getLogger(NinjaPurchaseTests.class);
        org.junit.runner.Result result = junit.run(NinjaPurchaseTests.class); // Replace "SampleTest" with the name of your class
        if (result.getFailureCount() > 0) {
        	logger.debug("Some tests were failed.");
            System.out.println("Test failed.");
            System.exit(1);
        } else {
        	logger.debug("All tests were passed.");
            System.out.println("Test finished successfully.");
            System.exit(0);
        }
    }
}
