package Ninja_Tests;

//Generated by Selenium IDE

import NinjaPages.NinjaAddToCart;
import NinjaPages.NinjaLoginPage;
import NinjaPages.NinjaRegisterPage;
import PagesContract.IAddToCartPage;
import PagesContract.ILoginPage;
import PagesContract.IRegisterPage;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.Test;
import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;
import org.junit.Before;
import org.junit.After;
import org.junit.Assert;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;

import java.nio.file.Paths;
import java.util.*;
import java.io.IOException;


public class NinjaSanityTests {
    private Logger logger;
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    JsonReader jsonReader;

    @Before
    public void setUp() throws IOException {
        System.setProperty("webdriver.chrome.driver", "src\\test\\resources\\chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        logger = LogManager.getLogger(NinjaSanityTests.class);
        jsonReader = new JsonReader();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    // function to success register:
    @Test
    public void register() {
    	logger.debug("##### Starting sanity tests! #####");
        logger.debug("### Starting Register Test! ###");
        IRegisterPage ninjaRegisterPage = new NinjaRegisterPage(driver);

        logger.debug("Reading test inputs from json");
        var testInputs = jsonReader.read("src/test/resources/RegisterTestInput.json");

        logger.debug("Navigating to registration page");
        ninjaRegisterPage.navigateToRegistrationPage();

        logger.debug("Filling registration details");
        ninjaRegisterPage.fillRegistrationDetails(testInputs);

        logger.debug("Clicking register");
        ninjaRegisterPage.clickRegister();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        logger.debug("Verify successfully registration");
        Assert.assertTrue(ninjaRegisterPage.isRegisterSuccessfully());        
        logger.debug("### Registration test finished successfully! ###");
    }

    @Test
    public void login() {
        logger.debug("### Starting Login Test! ###");
        ILoginPage ninjaLoginPage = new NinjaLoginPage(driver);

        logger.debug("Reading test inputs from json");
        var testInputs = jsonReader.read("src/test/resources/LoginTestInput.json");

        logger.debug("Navigating to login form");
        ninjaLoginPage.navigateToLoginForm();
        logger.debug("Enter user email");
        ninjaLoginPage.enterUserEmail(testInputs.get("input-email").toString());
        logger.debug("Enter user password");
        ninjaLoginPage.enterPassword(testInputs.get("input-password").toString());
        logger.debug("Click login");
        ninjaLoginPage.clickLogin();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        logger.debug("Verify successfully login");
        Assert.assertTrue(ninjaLoginPage.isLoginSuccessfully());
        logger.debug("### Login test finished successfully! ###");
        logger.debug("##### Sanity tests has finished successfully! #####");
    }

    @Test
    public void addToCart() {
        logger.debug("### Starting AddToCart Test! ###");
        IAddToCartPage ninjaLoginPage = new NinjaAddToCart(driver);
        logger.debug("Navigating to home page");
        ninjaLoginPage.navigateToHomePage();
        logger.debug("Adding product to cart");
        ninjaLoginPage.addProductToCart();
        logger.debug("Navigating to cart page");
        ninjaLoginPage.navigateToCartPage();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        logger.debug("Verify that the product was added successfully");
        Assert.assertTrue(ninjaLoginPage.verifyThatProductAdded());
        logger.debug("### Add to cart test finished successfully! ###");
    }


    public static void main(String args[]) {
        JUnitCore junit = new JUnitCore();
        junit.addListener(new TextListener(System.out));
        Logger logger = LogManager.getLogger(NinjaSanityTests.class);
        org.junit.runner.Result result = junit.run(NinjaSanityTests.class); // Replace "SampleTest" with the name of your class
        if (result.getFailureCount() > 0) {
        	logger.debug("Some tests were failed.");
            System.out.println("Test failed.");
            System.exit(1);
        } else {
        	logger.debug("All tests were passed.");
            System.out.println("Test finished successfully.");
            System.exit(0);
        }
    }
}
