package Ninja_Tests;

//Generated by Selenium IDE

import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.Test;
import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;
import org.junit.Before;
import org.junit.After;
import org.junit.Assert;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;

import java.nio.file.Paths;
import java.util.*;
import java.io.IOException;


public class RegisterTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() throws IOException {
        System.setProperty("webdriver.chrome.driver", "src\\test\\resources\\chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();

    }

    @After
    public void tearDown() {
        driver.quit();
    }

    // function to success register:
    //@Test
    public void register() {
        // Test name: Register test
        // Step # | name | target | value
        // 1 | open site
        driver.get("https://tutorialsninja.com/demo/index.php?route=common/home");
        // 2 | setWindowSize | 1052x666 |
        driver.findElement(By.xpath("//*[@id=\"top-links\"]/ul/li[2]/a")).click();
        //driver.manage().window().setSize(new Dimension(1052, 666));
        // 3 | type | name=q | hello
        driver.findElement(By.xpath("//*[@id=\"top-links\"]/ul/li[2]/ul/li[1]/a")).click();

        // Enter user name details:
        driver.findElement(By.id("input-firstname")).sendKeys("standard_user"); // input first name
        driver.findElement(By.id("input-lastname")).sendKeys("standard_user"); // input last name
        driver.findElement(By.id("input-email")).sendKeys("standard_user@gmail.com"); // input email
        driver.findElement(By.id("input-telephone")).sendKeys("standard_user"); // input telephone
        driver.findElement(By.id("input-password")).sendKeys("standard_user"); // input password
        driver.findElement(By.id("input-confirm")).sendKeys("standard_user"); // confirm password
        driver.findElement(By.name("agree")).click(); // click on agree checkbox
        driver.findElement(By.xpath("//*[@id=\"content\"]/form/div/div/input[2]")).click(); // click on continue button
        // should be navigated to success url:
        Assert.assertTrue(driver.getCurrentUrl().equals("https://tutorialsninja.com/demo/index.php?route=account/success"));
    }

    //@Test
    public void login() {
        // Test name: Register test
        // Step # | name | target | value
        // 1 | open site | / |
        driver.get("https://tutorialsninja.com/demo/index.php?route=common/home");
        // 2 | Click on my account
        driver.findElement(By.xpath("//*[@id=\"top-links\"]/ul/li[2]/a")).click();
        //driver.manage().window().setSize(new Dimension(1052, 666));
        // 3 | Click on login
        driver.findElement(By.xpath("//*[@id=\"top-links\"]/ul/li[2]/ul/li[2]/a")).click();
        // Enter user name details:
        driver.findElement(By.id("input-email")).sendKeys("standard_user@gmail.com"); // input email
        driver.findElement(By.id("input-password")).sendKeys("standard_user"); // input password
        // click on continue button
        driver.findElement(By.xpath("//*[@id=\"content\"]/div/div[2]/div/form/input")).click(); // click on continue button
//	 // should be navigated to success url	
        Assert.assertTrue(driver.getCurrentUrl().equals("https://tutorialsninja.com/demo/index.php?route=account/account"));
    }

    //@Test
    public void addToCart() {
        // Test name: Register test
        // Step # | name | target | value
        // 1 | open site | / |
        driver.get("https://tutorialsninja.com/demo/index.php?route=common/home");
        // 2 | Click add to cart on iphone button
        driver.findElement(By.xpath("//*[@id=\"content\"]/div[2]/div[2]/div/div[3]/button[1]")).click();

        // 3 | Click on my cart
        driver.findElement(By.xpath("//*[@id=\"top-links\"]/ul/li[4]/a/i")).click();

        // can add verification of items in cart
    }

    @Test
    public void purchase() {
        // create object mapper instance
        ObjectMapper mapper = new ObjectMapper();
        Logger logger = LogManager.getLogger(RegisterTest.class);

        // read JSON file into a map
        logger.debug("Starting Purchase Tests");
        List<Map<?, ?>> map;
        try {
            logger.debug("Reading input file");
            map = mapper.readValue(Paths.get("src/test/resources/RegisterTestInput.json").toFile(), List.class);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        driver.get("https://tutorialsninja.com/demo/index.php?route=common/home");
        // add iphone to cart
        logger.debug("Adding IPhone to cart");
        driver.findElement(By.xpath("//*[@id=\"content\"]/div[2]/div[2]/div/div[3]/button[1]")).click();
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        // click on cart button
        logger.debug("Clicking on cart button");
        driver.findElement(By.xpath("//*[@id=\"top-links\"]/ul/li[4]/a/i")).click();
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        // click on checkout button
        logger.debug("Clicking on checkout button");
        driver.findElement(By.xpath("//*[@id=\"content\"]/div[3]/div[2]/a")).click();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        // choose checkout as guest
        logger.debug("Choosing checkout as guest");
        driver.findElement(By.xpath("//*[@id=\"collapse-checkout-option\"]/div/div/div[1]/div[2]/label")).click();
        // click on continue
        logger.debug("Click on continue");
        driver.findElement(By.id("button-account")).click();

        // fill checkout form
        try {
            Thread.sleep(1500);
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        // enter billing address
        var inputData = map.get(0);

        logger.debug("Entering billing address");
        logger.trace("Input : {}", inputData);

        driver.findElement(By.id("input-payment-firstname")).sendKeys(inputData.get("input-payment-firstname").toString()); // input first name
        driver.findElement(By.id("input-payment-lastname")).sendKeys(inputData.get("input-payment-lastname").toString()); // input first name
        driver.findElement(By.id("input-payment-address-1")).sendKeys(inputData.get("input-payment-address-1").toString()); // input first name
        driver.findElement(By.id("input-payment-city")).sendKeys(inputData.get("input-payment-city").toString()); // input email
        driver.findElement(By.id("input-payment-email")).sendKeys(inputData.get("input-payment-email").toString()); // input email
        driver.findElement(By.id("input-payment-telephone")).sendKeys(inputData.get("input-payment-telephone").toString()); // input telephone
        driver.findElement(By.id("input-payment-postcode")).sendKeys(inputData.get("input-payment-postcode").toString()); // input first name
        // fill checkout form
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        driver.findElement(By.id("input-payment-zone")).sendKeys("Angus"); // input first name

        // fill checkout form
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        logger.debug("Continue to delivery details");
        driver.findElement(By.id("button-guest")).click();
        try {
            Thread.sleep(1500);
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        logger.debug("Continue to delivery method");
        driver.findElement(By.id("button-shipping-method")).click();
        try {
            Thread.sleep(1500);
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        logger.debug("Check the \"Terms & condition\" check box");
        driver.findElement(By.xpath("//*[@id=\"collapse-payment-method\"]/div/div[2]/div/input[1]")).click();
        logger.debug("Continue to confirm order");
        driver.findElement(By.xpath("//*[@id=\"button-payment-method\"]")).click();
        try {
            Thread.sleep(1500);
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        //click on confirm button
        driver.findElement(By.xpath("//*[@id=\"button-confirm\"]")).click();
        try {
            Thread.sleep(1500);
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        logger.debug("Validate url success order");
        Assert.assertTrue(driver.getCurrentUrl().equals("https://tutorialsninja.com/demo/index.php?route=checkout/success"));
    }


    public static void main(String args[]) {
        JUnitCore junit = new JUnitCore();
        junit.addListener(new TextListener(System.out));
        org.junit.runner.Result result = junit.run(RegisterTest.class); // Replace "SampleTest" with the name of your class
        if (result.getFailureCount() > 0) {
            System.out.println("Test failed.");
            System.exit(1);
        } else {
            System.out.println("Test finished successfully.");
            System.exit(0);
        }
    }
}
