package Ninja_Tests;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;


/*import org.apache.log4j.FileAppender;
import org.apache.log4j.Layout;
import org.apache.log4j.Level;
import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;
import org.apache.log4j.SimpleLayout;*/




public class sauce_demo_test {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;	
	@Before
	public void setUp() throws IOException {
		System.setProperty("webdriver.chrome.driver","C:\\Users\\saarg\\Downloads\\chromedriver_win32\\chromedriver.exe");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	 
	}
	@After
	public void tearDown() {
	 driver.quit();
	}
	@Test
	public void t1() {
	 // Test name: t1
	 // Step # | name | target | value
	 // 1 | open | / | 
	 driver.get("https://www.saucedemo.com/");
	 // 2 | setWindowSize | 1052x666 | 
	 driver.manage().window().setSize(new Dimension(1052, 666));
	 // 3 | type | name=q | hello
	 driver.findElement(By.id("user-name")).sendKeys("standard_user");
	 // 4 | sendKeys | name=q | ${KEY_ENTER}
	 driver.findElement(By.name("password")).sendKeys("secret_sauce");
	 // 5 | runScript | window.scrollTo(0,1500) | 
	 js.executeScript("window.scrollTo(0,1500)");
	 // 6 | click on login button
	 driver.findElement(By.id("login-button")).click();
	 // 7 | find all inventories
	 List<WebElement> items = driver.findElements(By.cssSelector("div.inventory_item_name"));
	 Iterator<WebElement> itr = items.iterator();
	 List<WebElement> prices = driver.findElements(By.cssSelector("div.inventory_item_price"));
	 Iterator<WebElement> itr1 = prices.iterator();
	 while(itr.hasNext() && itr1.hasNext())
	 {
		 System.out.println("Item name: " + itr.next().getText() +", Price: " + itr1.next().getText());
	 }
	 
	 

	}
	


public static void main(String args[]) {
	  JUnitCore junit = new JUnitCore();
	  junit.addListener(new TextListener(System.out));
	  org.junit.runner.Result result = junit.run(sauce_demo_test.class); // Replace "SampleTest" with the name of your class
	  if (result.getFailureCount() > 0) {
	    System.out.println("Test failed.");
	    System.exit(1);
	  } else {
	    System.out.println("Test finished successfully.");
	    System.exit(0);
	  }
	}
}
